<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.29" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.29" PrivateAssets="all" />
    <PackageReference Include="MudBlazor" Version="9.8.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\" />
    <Folder Include="Layout\" />
    <Folder Include="Models\" />
    <Folder Include="Pages\" />
    <Folder Include="Services\" />
    <Folder Include="ViewModels\" />
    <Folder Include="wwwroot\NewFolder\" />
    <Folder Include="wwwroot\sample-data\" />
  </ItemGroup>

</Project>
